### ISSUE TITLE
Installment value invalid

### ISSUE THREAD

**Issue by maaxg** [xyanlucasx/jspagseguro#1]
Olá :+1: 
Atualmente estou com um problema relacionado ao installment.
# Installment value e quantity 
![cutToGit](https://user-images.githubusercontent.com/49838612/102541698-7efddf00-408f-11eb-9209-cebfa359b621.png)
 # Erro
![cutToGit1](https://user-images.githubusercontent.com/49838612/102541715-83c29300-408f-11eb-82b9-d47d070a3503.png)
# Amount
![cutToGit2](https://user-images.githubusercontent.com/49838612/102541720-84f3c000-408f-11eb-8b7f-06ce5183236a.png)

## Descrição
 - Acredito que seja algo relacionado a divisão do meu installment que não é idêntica, porém não encontrei nada olhando a função installmentConditions() que pudesse me ajudar.
 
Espero que possam me ajudar :)

**Comment by yan-vidal** [comment]
Já conseguiu resolver o problema?
Peço desculpas pela demora, acabei vendo somente agora, não sei se ainda é útil, mas fica a resposta pra caso alguem tenha o mesmo problema. 
Esse erro só ocorre quando o valor de parcelas multiplicado pela quantidade de parcelas retorna um valor difernete do valor total. Qualquer erro, mesmo de 1 centavo vai retornar isso, é do próprio pagseguro, esse erro só foi convertido de xml pra json antes de ser exibido, é um erro interno do pagseguro.
